#!/bin/bash
set -e -x

# Temporary work dir
tmpdir="`mktemp -d`"
cd "$tmpdir"

# Install prerequisites
export DEBIAN_FRONTEND=noninteractive
apt-get update -q --yes
apt-get install -q --yes logrotate vim-nox hardlink wget ca-certificates

# Download and install Chef's packages
wget -nv https://packages.chef.io/files/stable/chef-server/$CHEF_SERVER_CORE_VERSION/ubuntu/14.04/chef-server-core_$CHEF_SERVER_CORE_VERSION-1_amd64.deb 
wget -nv https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/10.04/x86_64/chef_$CHEF_VERSION-1_amd64.deb

sha1sum -c - <<EOF
$CHEF_SERVER_CORE_SHA1  chef-server-core_$CHEF_SERVER_CORE_VERSION-1_amd64.deb
$CHEF_SHA1  chef_$CHEF_VERSION-1_amd64.deb
EOF

dpkg -i chef-server-core_$CHEF_SERVER_CORE_VERSION-1_amd64.deb chef_$CHEF_VERSION-1_amd64.deb

# Extra setup
rm -rf /etc/opscode
mkdir -p /etc/cron.hourly
ln -sfv /var/opt/opscode/log /var/log/opscode
ln -sfv /var/opt/opscode/etc /etc/opscode
ln -sfv /opt/opscode/sv/logrotate /opt/opscode/service
ln -sfv /opt/opscode/embedded/bin/sv /opt/opscode/init/logrotate
chef-apply -e 'chef_gem "knife-opc"'

mv /resources/init.rb /init.rb
mkdir -p /.chef
mv /resources/chef-server.rb /.chef/chef-server.rb
mkdir -p /opt/opscode/sv
mv /resources/logrotate /opt/opscode/sv/logrotate
mkdir -p /etc/chef
mv /resources/knife.rb /etc/chef/knife.rb
mkdir -p /usr/local/bin/chef-server-backup
mv /resources/backup.sh /usr/local/bin/chef-server-backup/backup.sh

# Adding user chef
groupadd chef
useradd -g chef chef

# Adding user opscode
groupadd opscode
useradd -g opscode -d /opt/opscode/embedded -s /bin/sh opscode

# Adding user opscode-pgsql
groupadd opscode-pgsql
useradd -g opscode-pgsql -d /var/opt/opscode/postgresql -s /bin/sh opscode-pgsql

# Add entrypoint
mv /resources/entrypoint.sh /entrypoint.sh

# Cleanup
cd /
rm -rf $tmpdir /tmp/install.sh /var/lib/apt/lists/* /var/cache/apt/archives/*

# Initialization of chef
/opt/opscode/embedded/bin/ruby init.rb > /tmp/chef.log &
CHEF_PID=$!
grep -m 1 "INIT: Reconfiguration finished" <(tail -f /tmp/chef.log)

rm -rf /tmp/chef.log
rm -rf /var/opt/opscode/*
